12/21/2022 09:46:22 AM get_phone_registration: Service has no operation 'selectCmDevice'
12/21/2022 09:47:06 AM get_phone_registration: 'InitialZeep' object has no attribute 'selectCmDevice'
12/21/2022 09:48:40 AM get_phone_registration: 'InitialZeep' object has no attribute 'selectCmDevice'
12/21/2022 09:51:04 AM get_phone_registration: 'InitialZeep' object has no attribute 'selectCmDevice'
12/21/2022 09:55:40 AM get_phone_registration: 'InitialRISZeep' object has no attribute 'selectCmDevice'
12/21/2022 09:55:46 AM get_phone_registration: 'InitialRISZeep' object has no attribute 'selectCmDevice'
12/21/2022 11:18:32 AM get_gateway_detail 'MainWindow' object has no attribute 'listHuntPilot' 
12/21/2022 11:20:00 AM get_gateway_detail 'InitialZeep' object has no attribute 'listHuntPilot' 
12/21/2022 11:20:17 AM get_gateway_detail 'InitialZeep' object has no attribute 'listHuntPilot' 
12/21/2022 01:32:35 PM get_cuc_version HTTPSConnectionPool(host='10.10.20.18', port=443): Max retries exceeded with url: /vmrest/version (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000139240F1910>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')) 
12/21/2022 02:19:41 PM get_callhandlers Invalid URL 'https:///vmrest/handlers/callhandlers': No host supplied
12/21/2022 02:19:44 PM get_vm_users Invalid URL 'https:///vmrest/users/': No host supplied
12/21/2022 02:46:44 PM get_cucm_version HTTPSConnectionPool(host='10.10.20.1', port=8443): Max retries exceeded with url: /axl/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FE56381D30>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')) 
12/21/2022 03:49:20 PM get_phone_registration: HTTPSConnectionPool(host='10.10.20.1', port=8443): Max retries exceeded with url: /realtimeservice2/services/RISService70 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000255C909B940>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
12/21/2022 03:49:22 PM get_cucm_version HTTPSConnectionPool(host='10.10.20.1', port=8443): Max retries exceeded with url: /axl/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000255C90938E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')) 
12/21/2022 03:54:44 PM get_phones.py HTTPSConnectionPool(host='10.10.20.1', port=8443): Max retries exceeded with url: /axl/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000255C90D8B50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')) 
12/22/2022 11:49:09 AM get_onsite_alerts Invalid URL 'https:///cerappservices/service/cerl': No host supplied 
12/22/2022 11:49:32 AM get_cer_version Invalid URL 'https:///cerappservices/export/cerclustergroup/list': No host supplied 
